version: "3.8"
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: graphqlapi
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/data/db

  api:
    container_name: graphqlapi
    build: .
    ports:
      - 4000:4000

volumes:
  mongodata:
